export const appRoutes = {
  home: '/',
  adminLogin: '/admin/login',
  admin: '/admin',
  adminCalendar: '/admin/calendar',
  adminStays: '/admin/stays',
  adminSubmissions: '/admin/submissions',
  adminMaintenance: '/admin/maintenance',
  adminIssues: '/admin/issues',
  adminIssueDetail: '/admin/issues/:id',
  adminMore: '/admin/more',
  adminSubmissionDetail: '/admin/submissions/:id',
  adminStayImportCreate: '/admin/stays/imports/new',
  adminStayImportDetail: '/admin/stays/imports/:id',
  adminStayCreate: '/admin/stays/new',
  adminStayDetail: '/admin/stays/:id',
  adminProperties: '/admin/properties',
  adminPropertyCreate: '/admin/properties/new',
  adminPropertyDetail: '/admin/properties/:id',
  guest: '/guest',
  guestStay: '/guest/stay',
  staff: '/staff',
  draft: '/draft',
  connection: '/dev/connection',
} as const;
